#server:
#  port: 8000
#
#spring:
#  #数据库配置
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.113.148.39:3306/mall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=false
#    username: root
#    password: wgx
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 124.222.77.187:8848
#
##mybatis-plus配置
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto