spring:
  cloud:
    gateway:
      routes:
        #product服务
        - id: product
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        #member服务
        - id: member
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        #ware服务
        - id: ware
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        #other服务
        - id: other
          uri: lb://mall-other
          predicates:
            - Path=/api/other/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        #admin后台服务
        - id: admin
          uri: lb://mall-admin
          predicates:
            - Path=/api/**
        #host转发
        - id: host
          uri: lb://mall-product
          predicates:
            - Host=www.mall.com,mall.com,www.item.mall.com,item.mall.com
        - id: search_host
          uri: lb://mall-search
          predicates:
            - Host=www.search.mall.com,search.mall.com