server:
  port: 14000

spring:
  application:
    name: mall-auth
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.154.128:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.154.128
    port: 6379
    password: wgx
    connect-timeout: 15000
    timeout: 100s
    lettuce:
      shutdown-timeout: 100s
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 5
        min-idle: 0
  session:
    store-type: redis
    timeout: 1d

gitee:
  oauth:
    clientid: c94541ea28217f62d662a009f9b80533a8b99d6d18cbc971a1742a61c04c6abc
    clientsecret: 5b717f006d9c1eb3ade2ffb59e613a91f339a9085e3a50201f2b6c199ec5f20d
    callback: http://auth.mall.com/auth/callback
