#server:
#  port: 10000
#
#spring:
#  profiles:
#    active: dev
#  application:
#    name: mall-product
#  #数据库配置
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.113.148.39:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=false
#    username: root
#    password: wgx
#  #redis配置
#  redis:
#    #host: 192.168.154.128
#    host: 47.113.148.39
#    port: 6379
#    password: wgx
#    connect-timeout: 15000
#    timeout: 100s
#    lettuce:
#      shutdown-timeout: 100s
#      pool:
#        max-active: 8
#        max-wait: -1ms
#        max-idle: 5
#        min-idle: 0
#  #nacos配置
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 124.222.77.187:8848
#
##mybatis-plus配置
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 0
#      logic-not-delete-value: 1



#logging:
#  level:
#    com.wgx.mall: debug
spring:
  thymeleaf:
    cache: false
  redis:
    host: 192.168.154.128
#    host: 47.113.148.39
  cache:
    type: redis
    redis:
      time-to-live: 3600000
#      use-key-prefix: false
      cache-null-values: true

thread:
  core-size: 10
  max-size: 100
  keep-alive-time: 100
