server:
  port: 9000

spring:
  application:
    name: mall-order
  #\u6570\u636E\u5E93\u914D\u7F6E
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.148.39:3306/mall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: wgx
  #nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.154.128:8848


#mybatis-plus\u914D\u7F6E
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
